version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm ci

  build:
    commands:
      - npm run build
      - npm run test

  post_build:
    commands:
      - npm run cdk synth

artifacts:
  files:
    - 'cdk.out/**/*'
    - 'package.json'
    - 'package-lock.json'
    - 'node_modules/**/*'
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'
    - '.npm/**/*' 