AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  BedrockHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: bedrock-handler.handler
      Runtime: nodejs22.x
      Timeout: 30
      Environment:
        Variables:
          AWS_REGION: ap-southeast-2
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*' 